export default {
    "title": "Gig Booking",
    "slogan": "Une application pour connecter les événements aux artistes.  ",
    "section.problematic": "Problématique",
    "section.solution": "Solution",
    "section.advantages": "Avantages",
    "section.features": "Fonctionnalité",
    "section.sign-up-benefits": "Bénéfices de vous inscrire ",
    "section.contact-us": "Contacter-nous ",

    "problematic.musician.label": "Artistes musicaux",
    "problematic.musician.text": "Votre carrière musicale n’est pas satisfaisante? Avec la composition, les pratiques et l’enregistrement en studio, pas le temps de chercher des gigs. Tout est question de réseaux et d’image, mais comment l’accroitre?",
    "problematic.municipality.label": "Municipalité",
    "problematic.municipality.text": "Vous planifiez des évènements pour vos citoyens, mais chercher des artistes musicaux est compliqué et frustrant. Est-ce qu’ils vont offrir de la musique et du divertissement de qualité?",
    "problematic.entreprise.label": "Entreprise",
    "problematic.entreprise.text": "Vos 5 à 7 et vos évènements manquent de nouveauté? Vous voulez les rendre plus convoitant et remarquables? La qualité de l’ambiance est indispensable, mais vous ne savez pas comment la rendre délectable?",

    "solution.p1":"Notre solution; GigBooking.  ",
    "solution.p2":"Une plateforme qui relie les organisateur(trice)s d’évènements (municipalités, entreprises, promoteur(trice)s) aux artistes musicaux dans le but d’élargir l’appel d’offre et d’optimiser la recherche d’artistes.  ",
    "solution.p3":"Pour les artistes, il s’agit d’un réseaux conçu pour les aider à entreprendre leur carrière musicale. ",
    "solution.p4":"Pour les organisateur(trice)s, il s'agit d’un réseau conçu pour faciliter et diversifier la recherche d’artistes. ",

    "advantages.musician":"Artistes musicaux",
    "advantages.musician.p1":"Meilleure visibilité",
    "advantages.musician.p1.sp1":"Design professionnel",
    "advantages.musician.p1.sp2":"Recommandations",
    "advantages.musician.p2":"Contrats sécuritaires",
    "advantages.musician.p3":"Simplifie la recherche de gigs (appel d’offre)  ",
    "advantages.musician.p4":"Plus de temps pour la création et la pratique artistique ",
    "advantages.musician.p5":"Historique de votre carrière artistique ",
    "advantages.musician.p6":"Abonnement gratuit",
    "advantages.municipality-entreprise":"Municipalité/Entreprise",
    "advantages.municipality-entreprise.p1":"Faciliter et optimiser la recherche d’artistes  ",
    "advantages.municipality-entreprise.p1.sp1":"Économie du temps",
    "advantages.municipality-entreprise.p1.sp2":"Diversification des artistes",
    "advantages.municipality-entreprise.p1.sp3":"Outils de recherche spécialisés",
    "advantages.municipality-entreprise.p2":"Contrats sécuritaires",
    "advantages.municipality-entreprise.p3":"Trouver des artistes locaux",

    "features.musician":"Artistes musicaux",
    "features.musician.p1":"Création d’un profil personnalisé",
    "features.musician.p2":"Recommandations d’amélioration de sa visibilité",
    "features.musician.p3":"Création d’un groupe",
    "features.musician.p4":"Recherche d’évènements",
    "features.musician.p5":"Contacter des organisateur(trice)s d’évènements",
    "features.musician.p6":"Appliquer pour performer à un évènement",
    "features.musician.p7":"Trouver d’autres artistes ?",
    "features.municipality-entreprise":"Municipalité / Entreprise",
    "features.municipality-entreprise.p1":"Création d’un profil personnalisé",
    "features.municipality-entreprise.p2":"Organiser des évènements",
    "features.municipality-entreprise.p3":"Recherche d’artistes musicaux",
    "features.municipality-entreprise.p4":"Contacter des artistes musicaux",
    "features.municipality-entreprise.p5":"Engager des artistes musicaux",
    "features.municipality-entreprise.p6":"Suivie des contrats avec les artistes",
    "features.municipality-entreprise.p7":"Facturation en ligne",

    "section.sign-up-benefits.newsletter":"En savoir plus : l’infolettre ",
    "section.sign-up-benefits.newsletter.p1":"Suivre le développement de l’application : ",
    "section.sign-up-benefits.newsletter.p1.d1":" En vous inscrivant, vous recevrez des infolettres décrivant la progression du développement de l’application.",
    "section.sign-up-benefits.involvement":"S’impliquer : acteur(trice) de l’innovation",
    "section.sign-up-benefits.involvement.p1":"Suggestions, critiques :",
    "section.sign-up-benefits.involvement.p1.sp1":"Vous aurez la possibilité d’envoyer des commentaires ou des suggestions pour améliorer l’application lors de son développement.",
    "section.sign-up-benefits.involvement.p2":"Devenir bêta-testeur(euse)",
    "section.sign-up-benefits.involvement.p2.sp1":"Lorsque l’application entrera en phase bêta, vous serez parmi les premiers à tester l’application",
    "section.sign-up-benefits.involvement.p3":"Badge honorifique (VIP) :",
    "section.sign-up-benefits.involvement.p3.sp1":"Lorsque l’application sera en ligne, Un badge unique vous sera assigné",
}